import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
} from "@/shadcn-ui/components/ui/navigation-menu";
import Link from "next/link";
import Image from "next/image";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="no" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="container mx-auto rounded-lg bg-blue-950/80 backdrop-blur py-4 px-2 fixed left-1/2 transform -translate-x-1/2 top-4 z-50">
            <NavigationMenu className="grid grid-cols-1 max-w-full">
              <NavigationMenuList className="justify-between w-full">
                <NavigationMenuItem>
                  <Link href="https://www.vestre-slidre.kommune.no/">
                    <Image
                      src="/images/header-logo.svg"
                      width={300}
                      height={60}
                      className="w-[235px] h-[44px] object-contain"
                      alt="Logo"
                    />
                  </Link>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <ModeToggle />
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </header>
          <main
            style={{
              backgroundImage:
                "radial-gradient(circle at 70% 50%, rgb(28 138 255 / 30%), transparent 50%), radial-gradient(circle at 100% 60%, rgb(152 73 248 / 40%), transparent 35%)",
            }}
          >
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
